name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest  # depext issue for gnuplot/jemalloc?
          #- macos-latest # slow
        ocaml-compiler:
          - 4.12.x
          - 5.0.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam depext -y benchpress benchpress-server
    - run: opam install . --deps-only
    - run: opam exec -- dune build @all --ignore-promoted-rules
    - run: opam exec -- dune runtest -p benchpress
      if: ${{ matrix.os == 'ubuntu-latest' }}
